"""initial schema

Revision ID: af2bc3e21a4b
Revises: 
Create Date: 2026-08-23 05:19:14.207340
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'af2bc3e21a4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_log',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'event_key')
    )
    op.create_table('chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('alert_profile', sa.String(length=16), nullable=False),
    sa.Column('quiet_from', sa.Integer(), nullable=False),
    sa.Column('quiet_to', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gw_result',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('net_points', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('bench_points', sa.Integer(), nullable=False),
    sa.Column('transfer_cost', sa.Integer(), nullable=False),
    sa.Column('captain_element', sa.Integer(), nullable=True),
    sa.Column('captain_points', sa.Integer(), nullable=False),
    sa.Column('chip', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('league_id', 'event', 'entry_id')
    )
    op.create_table('identity',
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('display', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tg_user_id', 'entry_id')
    )
    op.create_table('league',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scoring', sa.String(length=8), nullable=True),
    sa.Column('start_event', sa.Integer(), nullable=False),
    sa.Column('admin_entry', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_message',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('view', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'message_id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_live_message')
    )
    op.create_table('live_snapshot',
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('element', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event', 'element')
    )
    op.create_table('manager',
    sa.Column('entry_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.Text(), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('picks',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entry_id', 'event')
    )
    op.create_table('chat_league',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'league_id')
    )
    op.create_index('ix_one_default_league_per_chat', 'chat_league', ['chat_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('league_manager',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['manager.entry_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id', 'entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_manager')
    op.drop_index('ix_one_default_league_per_chat', table_name='chat_league', postgresql_where=sa.text('is_default'))
    op.drop_table('chat_league')
    op.drop_table('picks')
    op.drop_table('manager')
    op.drop_table('live_snapshot')
    op.drop_table('live_message')
    op.drop_table('league')
    op.drop_table('identity')
    op.drop_table('gw_result')
    op.drop_table('chat')
    op.drop_table('alert_log')
    # ### end Alembic commands ###
